[pytest]
testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --json-report --json-report-file=report.json --html=report_raw.html --self-contained-html
