CREATE TABLE IF NOT EXISTS travel_guides (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  account_book_id INT DEFAULT NULL,
  title VARCHAR(200) NOT NULL,
  city VARCHAR(100) NOT NULL,
  days INT NOT NULL DEFAULT 3,
  budget INT DEFAULT NULL,
  travel_type VARCHAR(50) DEFAULT NULL,
  guide_data JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (account_book_id) REFERENCES account_books(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
